# Generated by Django 5.0.2 on 2024-02-28 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.IntegerField(choices=[(1, 'Cramps'), (2, 'Mood Swings'), (3, 'Fatigue')], db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Period Symptoms',
            },
        ),
        migrations.CreateModel(
            name='MenstrualCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('symptoms', models.ManyToManyField(blank=True, related_name='periods', to='tracker.periodsymptom')),
            ],
            options={
                'verbose_name_plural': 'Menstrual Cycles',
            },
        ),
    ]
