name: Run tests
on:
  push:
    branches: ["main"]
jobs:
  execute_tests:
    name: Install requirements and execute tests
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt update
      - name: Check out repo code
        run: actions/checkout@v3
      - name : Install requirements 
        run : pip install -r  requirements.txt 
      - name : Execute tests
        run : python3 manage.py test
